version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: attention-from-scratch:dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    command: /bin/bash
